# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

default:
  image: ubuntu:latest

before_script:
- uname -a

after_script:
- echo "After script section"

build_vim:
  stage: build
  script:
  - bash install.sh vim
  - vim --version

build_on_my_zsh:
  stage: build
  script:
  - bash install.sh oh-my-zsh

build_faster_zsh:
  stage: build
  script:
  - bash install.sh faster-zsh

build_tmux_docker:
  stage: build
  script:
  - bash install.sh tmux-docker
