# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: ubuntu:latest

before_script:
  - echo "Before script section"
  - uname -a

after_script:
  - echo "After script section"
  - vim --version

build_vim:
  stage: build
  script:
    - apt install vim
