# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options
image: ubuntu:latest

stages:
- test
- build

before_script:
- uname -a

after_script:
- echo "After script section"

test_config:
  stage: test
  before_script:
  - apt update -y && apt upgrade -y
  - apt install -y git curl tmux
  script:
  - bash install.sh vim
  - test -f ~/.vimrc
  - bash install.sh tmux-docker
  - test -d ~/.tmux/plugins

build_docker:
  image: docker:19.03.12
  stage: build
  services:
  - docker:19.03.12-dind
  script:
  - docker login -u $GITLAB_USER -p $GITLAB_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/haomingw/dotfiles:latest .
  - docker push registry.gitlab.com/haomingw/dotfiles:latest
