dist: bionic

env:
  global:
  - PYTHONUNBUFFERED=1

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/vim'
    - sourceline: 'ppa:neovim-ppa/stable'
    packages:
    - vim
    - neovim

before_script:
- lsb_release -a
- vim --version

script:
- bash install.sh vim

branches:
  only:
  - master
  - develop

git:
  quiet: true
