dist: bionic

env:
  global:
  - PYTHONUNBUFFERED=1

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/vim'
    - sourceline: 'ppa:neovim-ppa/stable'
    packages:
    - vim

before_script:
- vim --version

script:
- bash install.sh vim

branches:
  only:
  - master
  - /^release-\d+\.\d+$/

git:
  quiet: true
