dist: bionic

env:
  global:
  - PYTHONUNBUFFERED=1
  - CHSH=no

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/vim'
    - sourceline: 'ppa:neovim-ppa/stable'
    packages:
    - vim
    - neovim
    - zsh

before_script:
- lsb_release -a
- vim --version
- zsh --version

script:
- bash install.sh vim
- bash install.sh oh-my-zsh
- bash install.sh zsh-plugins

branches:
  only:
  - master
  - develop

git:
  quiet: true
