dist: bionic

env:
  global:
  - PYTHONUNBUFFERED=1

addons:
  apt:
    sources:
    - ppa:jonathonf/vim
    - ppa:neovim-ppa/stable
    packages:
    - vim

script:
- bash install.sh vim

branches:
  only:
  - master
  - /^release-\d+\.\d+$/

git:
  quiet: true
