dist: focal

env:
  global:
  - PYTHONUNBUFFERED=1
  - CHSH=no
  - AUTH_USERS=haomingw

addons:
  apt:
    sources:
    - sourceline: 'ppa:jonathonf/vim'
    packages:
    - vim
    - zsh
    - shellcheck
    - tmux

before_script:
- lsb_release -a
- vim --version
- zsh --version
- tmux -V

script:
- shellcheck *.sh
- bash install.sh vim
- bash install.sh oh-my-zsh
- bash install.sh faster-zsh
- bash install.sh tmux-docker

branches:
  only:
  - master

git:
  quiet: true
