#!/usr/bin/env bash

set -eu

source "$HOME/.common/functions"

should_ignore() {
  # ignore past records
  local name="$1"
  local target=${1%.gpg}
  local current

  current=$(date +"%Y")

  if [[ "$name" =~ [0-9]{4}.* ]] && [[ "$name" != *"$current"* ]]; then
    [ -f "$target" ] && return 0 || return 1
  fi
  return 1
}

main() {
  program_exists gpg || return 0

  local repo
  local f target

  repo=$(git rev-parse --show-toplevel)

  exec < /dev/tty
  # shellcheck disable=SC2044
  for f in $(find "$repo" -type f -name "*.gpg"); do
    if should_ignore "$f"; then
      msg "Ignoring $f"
      continue
    fi
    target=${f%.gpg}
    if [ -f "$target" ]; then
      confirm "File $target exists, overwrite?" || {
        msg "Not overwriting $target"
        continue
      }
    fi
    msg "Decrypting $f"
    gpg --decrypt "$f" > "$target"
  done
}

main
