#!/usr/bin/env bash

set -eu

source "$HOME/.common/functions"

should_ignore() {
  # ignore past records
  local name="$1"
  local current

  current=$(date +"%Y")

  if [[ "$name" =~ [0-9]{4}.* ]] && [[ "$name" != *"$current"* ]]; then
     return 0
  fi

  if [[ "$name" == *done* ]]; then
    return 0
  fi

  return 1
}

main() {
  program_exists gpg || return 0

  local change changes target

  exec < /dev/tty
  # shellcheck disable=SC2044
  changes=$(git diff --name-only HEAD@{0} HEAD@{1} | grep .gpg)
  for change in $changes; do
    target=${change%.gpg}

    if [ -f "$target" ]; then
      confirm "File $target exists, overwrite?" || {
        msg "Not overwriting $target"
        continue
      }
    fi
    msg "Decrypting $change"
    gpg --decrypt "$change" > "$target"
  done
}

main
