# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.2
    hooks:
    -   id: pylint
