require "options"
require "keymaps"
require "plugins"
require "commands"

require "config.autopairs"
require "config.gitsigns"
require "config.cmp"
require "config.lualine"
require "config.telescope"
