require "options"
require "keymaps"
require "plugins"
require "autocmds"

require "config.cmp"
require "config.commenter"
require "config.gitsigns"
require "config.lualine"
require "config.telescope"
require "config.treesitter"
require "config.lsp"
