# vim: set sw=2 ts=2 sts=2 et tw=78 foldmarker={{,}} foldmethod=marker:
# @author: Haoming Wang <haoming.exe@gmail.com>

# Imports {{

safe_source() { [[ -s "$1" ]] && source "$1" || true }

for ff in ~/.common/*; do
  safe_source "$ff"
done

safe_source ~/.zshenv.local

# }}

# Env {{

export EDITOR=vim
export CONDA_AUTO_ACTIVATE_BASE=false
export FZF_DEFAULT_COMMAND='find -type f ! -name "*.o"'

program_exists fd && {
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
  export FZF_CTRL_T_COMMAND='fd --type f --type d --hidden --follow --exclude .git'
}

program_exists nnn && {
  export NNN_BMS='d:~/Documents;c:~/Documents/code;l:~/Downloads'
}

is_linux && program_exists nvim && export EDITOR=nvim

is_macos && export GPG_TTY=$(tty)

export RBENV_VERSION=2.7.1

# }} // namespace env
