name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:jonathonf/vim
        sudo apt update
        sudo apt install vim zsh tmux mpv

    - name: Configure vim
      run:  |
        vim --version
        bash install.sh vim

    - name: Install Oh My Zsh
      run:  |
        zsh --version
        bash install.sh oh-my-zsh

    - name: Configure Oh My Zsh
      run:  bash install.sh zsh-plugins

    - name: Configure tmux-lf-mpv
      if:   startsWith(matrix.os, 'ubuntu')
      run:  |
        tmux -V
        mpv --version
        bash install.sh tmux-lf-mpv
