name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-vim:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install latest vim
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo add-apt-repository ppa:jonathonf/vim
        sudo apt update
        sudo apt install vim

    - name: Configure vim
      run:  |
        vim --version
        bash install.sh vim
