name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    env:
      AUTH_USERS: haomingw
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo add-apt-repository ppa:jonathonf/vim
        sudo apt update
        sudo apt install vim zsh tmux

    - name: Configure vim
      run:  |
        vim --version
        bash install.sh vim

    - name: Install and configure Oh My Zsh
      run:  |
        zsh --version
        bash install.sh oh-my-zsh

    - name: Configure faster-zsh
      run:  |
        bash install.sh faster-zsh

    - name: Configure tmux-docker
      if:   startsWith(matrix.os, 'ubuntu')
      run:  |
        tmux -V
        bash install.sh tmux-docker
