name: Mirror

on:
  schedule:
    - cron: "0 8 * * 1"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: Mirror update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PWD }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Commit changes if there are any
        run: |
          echo "Signing with gpg key ${{ steps.import_gpg.outputs.keyid }}"
          git config user.email "haoming.exe@gmail.com"
          git config user.name "Github Actions[bot]"
          git config --global pull.ff only
          git config --global pull.rebase false
          bash mirror.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: master
